# -*- coding: utf-8 -*-
"""MNE Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgdIoL3cvIh5hV1K0JuNkGG7AgsgonCm
"""

import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import mne

def generate_feature_distribution_report(data, report_path="feature_distribution_report.html"):
    numeric_data = data.select_dtypes(include=[np.number])
    num_cols = numeric_data.columns

    img_dir = "distribution_images"
    os.makedirs(img_dir, exist_ok=True)

    image_paths = []

    for col in num_cols:
        fig, ax = plt.subplots(figsize=(6, 4))
        sns.kdeplot(data=numeric_data, x=col, ax=ax, fill=True)
        ax.set_title(f'Distribution of {col}')
        fig.tight_layout()

        img_path = os.path.join(img_dir, f"{col}.png")
        fig.savefig(img_path)
        plt.close(fig)
        image_paths.append((col, img_path))

    report = mne.Report(title='Feature Distribution Report')

    for title, path in image_paths:
        report.add_image(path, title=title, section='Distributions')

    report.save(report_path, overwrite=True)
    print(f"✅ MNE report generated at: {report_path}")
